# Generated by Django 4.2.9 on 2024-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создано"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлено"),
        ),
    ]
