# Generated by Django 4.2.9 on 2024-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0004_alter_bid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("CD", "Создано"), ("PR", "В процессе"), ("PD", "Завершено")],
                default="CD",
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
