# Generated by Django 4.2.9 on 2024-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0002_alter_bid_created_alter_bid_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="problem",
            field=models.CharField(max_length=255, verbose_name="проблема"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("CD", "CREATED"), ("PR", "PROCESSING"), ("PD", "PASSED")],
                max_length=2,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="type_problem",
            field=models.CharField(max_length=255, verbose_name="тип проблемы"),
        ),
    ]
