# Generated by Django 4.2.9 on 2024-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0003_alter_bid_problem_alter_bid_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("CD", "Создано"), ("PR", "В процессе"), ("PD", "Завершено")],
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
